-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 13:23:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ilumiant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilumiant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilumiant` DEFAULT CHARACTER SET utf8 ;
USE `ilumiant` ;

-- -----------------------------------------------------
-- Table `ilumiant`.`ilumi_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilumiant`.`ilumi_cadastro` (
  `n_idcad` INT NOT NULL AUTO_INCREMENT,
  `c_cpfcad` VARCHAR(11) NOT NULL,
  `c_nomecad` VARCHAR(50) NOT NULL,
  `c_emailcad` VARCHAR(45) NOT NULL,
  `c_senhacad` VARCHAR(16) NOT NULL,
  `c_telefonecad` VARCHAR(12) NOT NULL,
  UNIQUE INDEX `c_emailcad_UNIQUE` (`c_emailcad` ASC) VISIBLE,
  UNIQUE INDEX `c_telefonecad_UNIQUE` (`c_telefonecad` ASC) VISIBLE,
  UNIQUE INDEX `c_cpfcad_UNIQUE` (`c_cpfcad` ASC) VISIBLE,
  PRIMARY KEY (`n_idcad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilumiant`.`ilumi_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilumiant`.`ilumi_user` (
  `n_iduser` INT NOT NULL AUTO_INCREMENT,
  `n_idcad` INT NOT NULL,
  `c_enderecouser` VARCHAR(150) NOT NULL,
  `d_nasciuser` DATE NOT NULL,
  `c_estadouser` VARCHAR(2) NOT NULL,
  `c_cidadeuser` VARCHAR(30) NOT NULL,
  `c_imguser` VARCHAR(250) NOT NULL,
  `c_prestserv` TINYINT(1) NOT NULL,
  PRIMARY KEY (`n_iduser`),
  INDEX `fk_ilumi_user_ilumi_cadastro1_idx` (`n_idcad` ASC) VISIBLE,
  CONSTRAINT `fk_ilumi_user_ilumi_cadastro1`
    FOREIGN KEY (`n_idcad`)
    REFERENCES `ilumiant`.`ilumi_cadastro` (`n_idcad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilumiant`.`ilumi_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilumiant`.`ilumi_servicos` (
  `n_idservi` INT NOT NULL AUTO_INCREMENT,
  `c_nomeservi` VARCHAR(40) NOT NULL,
  `c_descservi` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`n_idservi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilumiant`.`ilumi_servforn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilumiant`.`ilumi_servforn` (
  `n_idservforn` INT NOT NULL AUTO_INCREMENT,
  `n_iduser` INT NOT NULL,
  `n_idservi` INT NOT NULL,
  `n_cnpjcad` VARCHAR(14) NULL,
  `c_descservi` VARCHAR(300) NULL,
  `c_formaservi` VARCHAR(12) NOT NULL,
  `c_estadoservi` VARCHAR(2) NULL,
  `c_cidadeservi` VARCHAR(30) NULL,
  `c_imgservia` VARCHAR(250) NULL,
  `c_imgservib` VARCHAR(250) NULL,
  `c_imgservic` VARCHAR(250) NULL,
  `c_imgservid` VARCHAR(250) NULL,
  INDEX `fk_ilumi_servforn_ilumi_serviços1_idx` (`n_idservi` ASC) VISIBLE,
  INDEX `fk_ilumi_servforn_ilumi_user1_idx` (`n_iduser` ASC) VISIBLE,
  PRIMARY KEY (`n_idservforn`),
  CONSTRAINT `fk_ilumi_servforn_ilumi_serviços1`
    FOREIGN KEY (`n_idservi`)
    REFERENCES `ilumiant`.`ilumi_servicos` (`n_idservi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ilumi_servforn_ilumi_user1`
    FOREIGN KEY (`n_iduser`)
    REFERENCES `ilumiant`.`ilumi_user` (`n_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilumiant`.`ilumi_avali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilumiant`.`ilumi_avali` (
  `n_iduser` INT NOT NULL,
  `n_idservforn` INT NOT NULL,
  `n_pontavali` FLOAT(2,1) NOT NULL,
  `c_comentavali` VARCHAR(255) NULL,
  INDEX `fk_ilumi_avali_ilumi_user1_idx` (`n_iduser` ASC) VISIBLE,
  INDEX `fk_ilumi_avali_ilumi_servforn1_idx` (`n_idservforn` ASC) VISIBLE,
  CONSTRAINT `fk_ilumi_avali_ilumi_user1`
    FOREIGN KEY (`n_iduser`)
    REFERENCES `ilumiant`.`ilumi_user` (`n_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ilumi_avali_ilumi_servforn1`
    FOREIGN KEY (`n_idservforn`)
    REFERENCES `ilumiant`.`ilumi_servforn` (`n_idservforn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
